#!/usr/bin/env ruby

Dir.chdir __dir__ do
    require 'bundler/setup'
    require 'dotenv/load'
    require 'active_record'
    require 'require_all'
end

require 'ostruct'
require 'fcntl'

puts 'Connecting to database'

ActiveRecord::Base.establish_connection(ENV['MAGICARPI_DB'])

if ENV['DEBUG']
    require 'logger'
    ActiveRecord::Base.logger = Logger.new(STDOUT)
end

require_rel 'lib'

puts 'Starting GPS'

Thread.new do
    begin
        GpsScanner.run
    rescue => e
        puts 'GpsScanner broke!'
        pp e
    end
end

# Give the GPS scanner a few seconds.
sleep 5

puts 'Starting network scanner'

Thread.new do
    begin
        NetworkScanner.run
    rescue => e
        puts 'NetworkScanner broke!'
        pp e
    end
end

puts 'Startup finished'

# Nothing to do. May as well relax.
# puts 'Main thread is going to sleep... zzz'
loop { sleep 5 }
