#!/usr/bin/env ruby

Dir.chdir __dir__ do
    require 'bundler/setup'
    require 'dotenv/load'
    require 'active_record'
    require 'require_all'
end

require 'ostruct'
require 'fcntl'

puts 'Connecting to database'

ActiveRecord::Base.establish_connection(ENV['MAGICARPI_DB'])

if ENV['DEBUG']
    require 'logger'
    ActiveRecord::Base.logger = Logger.new(STDOUT)
end

require_rel 'lib'

puts 'Starting GPS'

Thread.new do
    GpsScanner.run
end

# Give the GPS scanner a few seconds to start.
sleep 5

puts 'Starting network scanner'

Thread.new do
    NetworkScanner.run
end

puts 'Starting time service'

Thread.new do
    TimeService.run
end

puts 'Startup finished'

# Nothing to do. May as well relax.
# puts 'Main thread is going to sleep... zzz'
loop do
    sleep 5
end
